
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspaceTemplate
metadata:
  name: theia-ide-workspace-tl500
  namespace: tl500-devspaces
spec:
  commands:
    - apply:
        component: remote-runtime-injector
      id: init-container-command
  components:
    - attributes: {}
      container:
        cpuRequest: 100m
        env:
          - name: THEIA_PLUGINS
            value: 'local-dir:///plugins'
          - name: HOSTED_PLUGIN_HOSTNAME
            value: 0.0.0.0
          - name: HOSTED_PLUGIN_PORT
            value: '3130'
          - name: THEIA_HOST
            value: 127.0.0.1
        sourceMapping: /projects
        volumeMounts:
          - name: plugins
            path: /plugins
          - name: theia-local
            path: /home/theia/.theia
        image: >-
          registry.redhat.io/devspaces/theia-rhel8@sha256:c050b7779451703a4067fca77df5325e9fba91178ec723d4e878ab912c9e56ba
        endpoints:
          - attributes:
              cookiesAuthEnabled: true
              discoverable: false
              type: main
              urlRewriteSupported: true
            exposure: public
            name: theia
            protocol: https
            secure: false
            targetPort: 3100
          - attributes:
              cookiesAuthEnabled: true
              discoverable: false
              type: webview
              unique: true
              urlRewriteSupported: true
            exposure: public
            name: webviews
            protocol: https
            secure: false
            targetPort: 3100
          - attributes:
              cookiesAuthEnabled: true
              discoverable: false
              type: mini-browser
              unique: true
              urlRewriteSupported: true
            exposure: public
            name: mini-browser
            protocol: https
            secure: false
            targetPort: 3100
          - attributes:
              discoverable: false
              type: ide-dev
              urlRewriteSupported: true
            exposure: public
            name: theia-dev
            protocol: http
            targetPort: 3130
          - attributes:
              discoverable: false
              urlRewriteSupported: true
            exposure: public
            name: theia-redirect-1
            protocol: http
            targetPort: 13131
          - attributes:
              discoverable: false
              urlRewriteSupported: true
            exposure: public
            name: theia-redirect-2
            protocol: http
            targetPort: 13132
          - attributes:
              discoverable: false
              urlRewriteSupported: true
            exposure: public
            name: theia-redirect-3
            protocol: http
            targetPort: 13133
          - attributes:
              cookiesAuthEnabled: true
              discoverable: false
              type: collocated-terminal
              urlRewriteSupported: true
            exposure: public
            name: terminal
            protocol: wss
            secure: false
            targetPort: 3333
        mountSources: true
      name: theia-ide
    - name: plugins
      volume: {}
    - name: theia-local
      volume: {}
    - attributes: {}
      container:
        command:
          - /go/bin/che-machine-exec
          - '--url'
          - '127.0.0.1:3333'
          - '--idle-timeout'
          - 30m
        cpuLimit: 500m
        cpuRequest: 30m
        image: >-
          registry.redhat.io/devspaces/machineexec-rhel8@sha256:f849e92075ccb720ea211691d379a381fdb158c25e083a219a711278d3614981
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        sourceMapping: /projects
      name: che-machine-exec
    - container:
        cpuLimit: 500m
        cpuRequest: 30m
        env:
          - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
            value: /remote-endpoint/plugin-remote-endpoint
          - name: REMOTE_ENDPOINT_VOLUME_NAME
            value: remote-endpoint
        image: >-
          registry.redhat.io/devspaces/theia-endpoint-rhel8@sha256:2d927b80a8f7cc9df7313e2b137559a797ecb82ef114bea16efae1d087a32254
        memoryLimit: 128Mi
        memoryRequest: 32Mi
        sourceMapping: /projects
        volumeMounts:
          - name: plugins
            path: /plugins
          - name: remote-endpoint
            path: /remote-endpoint
      name: remote-runtime-injector
    - name: remote-endpoint
      volume:
        ephemeral: true
  events:
    preStart:
      - init-container-command
---
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: tl500
  namespace: tl500-devspaces
spec:
  routingClass: che
  started: true
  template:
    attributes:
      dw.metadata.annotations:
        app.kubernetes.io/name: tl500
    components:
      - container:
          args:
            - /bin/sh
            - '-c'
            - sleep infinity
          image: 'quay.io/rht-labs/stack-tl500:3.0.16'
          memoryLimit: 2Gi
          mountSources: true
          sourceMapping: /projects
          volumeMounts:
            - name: projects
              path: /projects
            - name: config
              path: /home/developer/.config
            - name: npm
              path: /home/developer/.npm
        name: stack-tl500
      - name: projects
        volume: {}
      - name: config
        volume: {}
      - name: npm
        volume: {}
      - name: theia-ide-workspace-tl500
        plugin:
          kubernetes:
            name: theia-ide-workspace-tl500
    projects:
      - git:
          remotes:
            origin: 'https://github.com/rht-labs/tech-exercise.git'
        name: tech-exercise
