---
apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: {{ .Values.logging.namespace }}
stringData:
  access_key_id: minio
  access_key_secret: IJrixDGbADAkgey5
  bucketnames: loki
  endpoint: http://minio-service.tl500-minio.svc.cluster.local:9000
  region: eu-central-1